trigger: none

pool:
  # 'AgentPool_VmssUbuntu'
  vmImage: 'ubuntu-latest'

variables:
  file_name: 'abc.csv'
  is_star: 'True'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.14'
  displayName: 'Set up Python 3.13.14'

- script: |
    cd DMS_ParamListGenerator
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python working_pipeline.py "$(file_name)" "$(is_star)"
  displayName: 'Install dependencies and run script'