trigger:
- none

parameters:
  - name: fileName
    displayName: 'Target file name (e.g. star_target.txt)'
    type: string
    default: 'pipeline_test.txt'

  - name: isStar
    displayName: 'Is this a list of STAR codes?'
    type: string
    default: 'no'
    values:
      - 'yes'
      - 'no'

pool: 'AgentPool_VmssUbuntu'

variables:
  storage_account: 'ecdcncisst'
  storage_container: 'ethan-resources'
  working_dir: 'DMS_ParamListGenerator'
  # group: ethans_secrets

jobs:
  - job: RunParamListGenerator
    variables:   # syntax limitation has to be here
      - group: ethan_secrets
    steps:
      - task: AzureCLI@2
        displayName: 'Download resource from NCIS blob storage'
        inputs:
          azureSubscription: 'DevOpsServiceConnection_EcDc-NCIS-rg'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az storage blob download \
              --account-name $(storage_account) \
              --container-name $(storage_container) \
              --name ${{ parameters.fileName }} \
              --file $(working_dir)/${{ parameters.fileName }}
            cat "$(working_dir)/${{ parameters.fileName }}"

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.13.14'
        displayName: 'Set up Python 3.13.14'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python working_pipeline.py "${{ parameters.fileName }}" "${{ parameters.isStar }}"
        displayName: 'Install dependencies, run script, and upload output'
        workingDirectory: $(working_dir)
        env:
          MY_SECRET: $(connection_string)