#keyforwhatshouldbethefinalcolumnmapping-feedascoltitles?
output_col_mapping={"DatasetName":datasetName,
"MonitoringLocationID": monitoringLocationID,
"MonitoringLocationName": "Station Name",
"MonitoringLocationLatitude":"Station Latitude",
"MonitoringLocationLongitude":"Station Longitude",
"MonitoringLocationHorizontalCoordinateReferenceSystem": coordRefSystem_Horizontal,
"MonitoringLocationHorizontalAccuracyMeasure": None,
"MonitoringLocationHorizontalAccuracyUnit": None,
"MonitoringLocationType": locationType,
"ActivityType": activityType,
"ActivityMediaName": "Matrix",
"ActivityStartDate": "Sample Date",
"ActivityStartTime": "Sample Date",
"ActivityStartTimeZone":timeZone,
"ActivityEndDate": "Sample Date",
"ActivityEndTime": "Sample Date",
"ActivityEndTimeZone": timeZone,
"ActivityDepthHeightMeasure": None,
"ActivityDepthHeightUnit": None,
"SampleCollectionEquipmentName": None,
"CharacteristicName": "Parameter",
"MethodSpeciation":None,
"ResultSampleFraction":None,
"ResultValue": "Measurement Value",
"ResultUnit":None,           # Will need to reconsider grouping in main file
"ResultValueType":None,   # required
"ResultDetectionCondition":None,
"ResultDetectionQuantitationLimitMeasure":None,
"ResultDetectionQuantitationLimitUnit":None,
"ResultDetectionQuantitationLimitType":None,
"ResultStatusID":None,
"ResultComment":None,
"ResultAnalyticalMethodID":None,
"ResultAnalyticalMethodContext":None,
"ResultAnalyticalMethodName":None,
"AnalysisStartDate":None,
"AnalysisStartTime":None,
"AnalysisStartTimeZone":None,
"LaboratoryName":None,
"LaboratorySampleID":None,
}
